<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Application/Rudoger.Modules.Inventory.Application.csproj" />
    <ProjectReference Include="../Domain/Rudoger.Modules.Inventory.Domain.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Infrastructure/Rudoger.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="../../Product/Presentation/Rudoger.Modules.Product.Presentation.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
  </ItemGroup>
</Project>
