<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Domain/Rudoger.Modules.Authn.Domain.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Application/Rudoger.BuildingBlocks.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Identity.Core" />
  </ItemGroup>
</Project>
